import Color from 'color';
import theme from '../@vex/utils/tailwindcss';

export const aioTableLabels = [
  {
    text: 'CAPTURA',
    backgroundColor: Color(theme.colors.green['500']).fade(0.9),
    color: theme.colors.green['500']
  },
  {
    text: 'EN PROCESO',
    backgroundColor: Color(theme.colors.cyan['500']).fade(0.9),
    color: theme.colors.cyan['500']
  },
  {
    text: 'APROBADO',
    backgroundColor: Color(theme.colors.teal['500']).fade(0.9),
    color: theme.colors.teal['500']
  },
  {
    text: 'CANCELADO',
    backgroundColor: Color(theme.colors.purple['500']).fade(0.9),
    color: theme.colors.purple['500']
  },
];

export const aioTableData = [
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0], aioTableLabels[1]]
  },
  {
    folio: 17060076,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060077,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060078,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060079,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060080,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060081,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[2]]
  },
  {
    folio: 17060082,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0], aioTableLabels[1]]
  },
  {
    folio: 17060083,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060084,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
  },
  {
    folio: 17060085,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060086,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060086,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060088,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060089,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[2]]
  },
  {
    folio: 17060090,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060091,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060092,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060093,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060094,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[2]]
  },
  {
    folio: 17060095,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060096,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060097,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060098,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels : [aioTableLabels[0]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[3]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[0]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[1]]
  },
  {
    folio: 17060075,
    producto: 'Comercial',
    origen: 'Asignación',
    tipoInmueble: 'Casa habitación',
    valuador: 'Rubén Pérez',
    responsable: 'Rubén Pérez',
    propietario: 'Rubén Pérez',
    solicitante:'Rubén Pérez',
    fecha: '13/03/2020',
    labels: [aioTableLabels[2]]
  }
];
